# Generated by Django 2.2.5 on 2019-09-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_class', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
