# Generated by Django 2.2.5 on 2019-09-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('H', 'Heroic'), ('L', 'Legendary')], default='E', max_length=1)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Hero')),
            ],
        ),
    ]
