# Generated by Django 2.2.5 on 2019-09-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='description',
        ),
    ]
