# Generated by Django 2.2.5 on 2019-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_quest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
