# Generated by Django 2.2.5 on 2019-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190922_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('H', 'Heroic'), ('L', 'Legendary')], default='E', max_length=1),
        ),
    ]
