# Generated by Django 2.2.5 on 2019-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='quests',
            field=models.ManyToManyField(to='main_app.Quest'),
        ),
    ]
